language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
script:
  - coverage run -m unittest discover tests.py
before_install:
  - pip install codecov
after_success:
  - codecov
